version: '3.7'
services:
    db:
      image: postgres:12-alpine
      container_name: postgres
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=postgres
      volumes:
        - db_data:/var/lib/postgresql/data
      ports:
        - 5432:5432
    
    redis:
      image: redis:6.2.1-alpine
      container_name: redis
      command: redis-server --requirepass redis
      ports:
        - 6379:6379


volumes:
  db_data: